Add 245 and 512 Breakout Boards
LibrePCB-Libraries/Adafruit.lplib pull request #8
Opened 2020-04-20 07:36 UTC by Stemby

##### SUMMARY
Added 245 and 512 Breakout Boards (analog joysticks).

##### OPEN QUESTIONS / UNRESOLVED ISSUES
Packages are sketchy.

##### CHECKLIST

- [X] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [ ] For packages, I followed IPC7351C (see details in library conventions).
- [X] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [X] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

2020-10-02 12:37 UTC, dbrgn requested changes
Thanks @Stemby for the contribution, and sorry for the loong review delay!

- Symbols:
  - They look good to me, but I wonder if they should be moved to the base library. What do you think, @ubruhin?
  - Additionally, I'd move VCC/GND to the left side (VCC on top, GND at the bottom) and the outputs to the right side.
- Components:
  - Same thing here, should they be moved to the base lib? @ubruhin 

Regarding the package, the footprint of the 245 looks totally different to me...

PCB:

![img](https://tmp.dbrgn.ch/screenshot-20201002-143135.png)

Package:

![img](https://tmp.dbrgn.ch/screenshot-20201002-143146.png)

2020-10-02 12:37 UTC, dbrgn commented on pkg/df89cc5c-aef5-440c-bf14-13ed199bd265/package.lp
> + (name "Adafruit 512 Breakboard")
According to the IPC standard, this should be:

```suggestion
 (name "ADAFRUIT_512")
```

2020-10-02 12:37 UTC, dbrgn commented on dev/8954aa9e-7042-4ba8-aac4-cff090493d5b/device.lp
> + (name "Adafruit 245 Breakout")
According to the IPC standard, this should be

```suggestion
 (name "ADAFRUIT_245")
```

2020-10-02 12:37 UTC, dbrgn commented on pkg/df89cc5c-aef5-440c-bf14-13ed199bd265/package.lp
> +   (align center bottom) (position 0.0 22.86) (rotation 0.0)
I'd move this down half a step:

```suggestion
   (align center bottom) (position 0.0 21.59) (rotation 0.0)
```

2020-10-02 12:37 UTC, dbrgn commented on pkg/df89cc5c-aef5-440c-bf14-13ed199bd265/package.lp
> +   (align center top) (position 0.0 -22.86) (rotation 0.0)
I'd move this up half a step:

```suggestion
   (align center top) (position 0.0 -21.59) (rotation 0.0)
```

2020-10-06 21:15 UTC, ubruhin commented
> Symbols:
>        They look good to me, but I wonder if they should be moved to the base library. What do you think, @ubruhin?
>        Additionally, I'd move VCC/GND to the left side (VCC on top, GND at the bottom) and the outputs to the right side.
>    Components:
>        Same thing here, should they be moved to the base lib? @ubruhin

Yeah, since these look very generic, I think that makes sense! But I'd suggest some small changes:
- Maybe make the signal names slightly more expressive, at least the `S` could be renamed to `SEL` or `BTN` or so.
- Change the default value from `{{PARTNUMBER or DEVICE or COMPONENT}}` to `{{PARTNUMBER or DEVICE}}` since the component name is too generic to be useful in a schematic.

@Stemby Do you like to apply these changes and move the symbols and components to the base library? Or should we take care of that?

2021-01-07 12:42 UTC, rnestler commented
@Stemby are you still active on this?

2023-10-16 12:44 UTC, ubruhin commented
I extracted the sym/cmp to the base library: https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/131

Now closing this due to inactivity (the packages would require some rework to get them finished).

2023-10-16 12:44 UTC, closed without merging